(cl:defpackage sena_msgs-srv
  (:use )
  (:export
   "BALLHANDLE"
   "<BALLHANDLE-REQUEST>"
   "BALLHANDLE-REQUEST"
   "<BALLHANDLE-RESPONSE>"
   "BALLHANDLE-RESPONSE"
   "KINEMATICSFORWARD"
   "<KINEMATICSFORWARD-REQUEST>"
   "KINEMATICSFORWARD-REQUEST"
   "<KINEMATICSFORWARD-RESPONSE>"
   "KINEMATICSFORWARD-RESPONSE"
   "KINEMATICSINVERSE"
   "<KINEMATICSINVERSE-REQUEST>"
   "KINEMATICSINVERSE-REQUEST"
   "<KINEMATICSINVERSE-RESPONSE>"
   "KINEMATICSINVERSE-RESPONSE"
   "SHOOT"
   "<SHOOT-REQUEST>"
   "SHOOT-REQUEST"
   "<SHOOT-RESPONSE>"
   "SHOOT-RESPONSE"
  ))

